[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
linker = "riscv64-unknown-elf-ld"
runner = "qemu-system-riscv64 -nographic -machine virt -m 2048 -smp 4 -kernel"
